baseurl: /blog

author: 嗣宗

motto: 剖竹十日间，一朝风化清。

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: /:year/:month/:day/:title
