baseurl: /blog

author: 嗣宗

collections:
  authors:
    output: true
  categories:
    output: true

defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: /:categories/:year/:month/:day/:title/
